Create API
limavfabio/VenomPrecision-back-end pull request #25
Opened 2023-06-22 21:07 UTC by anderCM

#### Technical set up

- Set up the repository/repositories on GitHub and use Gitflow.
- You should use Postgres as your database
- Use Rails to create backend API.
- The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.
-  Add full documentation for your API.
- Add validations.
- Add unit tests for models and controllers.
- Validate parameters in controllers, models and migrations.

2023-06-23 02:05 UTC, mcrd25 requested changes
Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- You seem to have met all functional requirements 👍 
- Have API documentation 👍 
- Implemented routes well 👍 
- Your code is clean enough 👍 

## Required Changes ♻️
_Check the comments under the review._
- Make sure to ensure all tests are passing before code reviews, if this is something you need extra support with, please do let me know

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] removing the `test` directory since you are using `rspec` for testing and not native testing.
- [OPTIONAL] Consider using the `timecop` gem to freeze time when running tests. It can help avoid errors: https://github.com/travisjeffery/timecop
- [OPTIONAL] Should always have positive and negative tests to ensure it works the way you expect it. Eg. What do you expect the output to be when it's not valid or when valid etc.
Consider making all your tests more extensive, not just this one. For this simple application, it may not catch a possible crippling bug, but in bigger applications, it definitely can. Consider this for all projects moving forward.


**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 02:05 UTC, mcrd25 commented on app/controllers/api/v1/reservations_controller.rb
> +    @reservation.destroy
What happens if it is not destroyed successfully?

2023-06-23 02:05 UTC, mcrd25 commented on app/controllers/api/v1/users_controller.rb
> +    @user.destroy
What happens if it is not destroyed successfully?

2023-06-23 13:33 UTC, chelobotix commented on spec/models/reservation_spec.rb
> +  end
Hello @mcrd25, the problem has been fixed.
Thank you

2023-06-23 13:48 UTC, chelobotix commented on spec/integration/api/v1/reservations_spec.rb
> +  end
@mcrd25, just wanted to give you a heads-up that the integration folder tests were automatically created by Rswag to help with API-Documentation. For the correct type of request tests, you can find them in the Request folder. Thanks!

2023-06-23 13:56 UTC, chelobotix commented on spec/integration/api/v1/products_spec.rb
> +end
@mcrd25, just wanted to give you a heads-up that the integration folder tests were automatically created by Rswag to help with API-Documentation. For the correct type of request tests, you can find them in the Request folder. Thanks!

2023-06-23 13:56 UTC, chelobotix commented on spec/integration/api/v1/users_spec.rb
> +  end
@mcrd25, just wanted to give you a heads-up that the integration folder tests were automatically created by Rswag to help with API-Documentation. For the correct type of request tests, you can find them in the Request folder. Thanks!

2023-06-23 16:02 UTC, chelobotix commented on spec/requests/api/v1/product_spec.rb
> +      expect(response).to have_http_status(:success)
Hello @mcrd25, the problem has been fixed.
Thank you

2023-06-23 16:02 UTC, chelobotix commented on spec/requests/api/v1/reservation_spec.rb
> +  end
Hello @mcrd25, the problem has been fixed.
Thank you

2023-06-23 16:53 UTC, anderCM commented on app/controllers/api/v1/users_controller.rb
> +    @user.destroy
@mcrd25  We have added a validation and returning a custom message if the user is destroyed
```
  def destroy
    if @user.destroy
      render json: { status: 'success', message: 'The user has been deleted' }
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end
  ```

2023-06-23 16:54 UTC, anderCM commented on app/controllers/api/v1/reservations_controller.rb
> +    @reservation.destroy
@mcrd25  We have added a validation and returning a custom message if the reservation is destroyed
```
  def destroy
    if @reservation.destroy
      render json: { status: 'success', message: 'The reservation has been deleted' }
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end
  ```

2023-06-23 16:55 UTC, anderCM commented on spec/requests/api/v1/user_spec.rb
> +end
@mcrd25  We have fixed these issues, now all tests are passing

2023-06-24 18:29 UTC, Meltrust approved these changes
#### Hi team,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Failure/error handling for `destroy` has been implemented ✔️ 
- Tests are now passing✔️ 
- rswag generated files have been excluded from the rspec command avoiding questionable test runs✔️ 
- Great job✔️ 



Cheers and Happy coding!👏👏👏


------

2023-06-24 18:29 UTC, Meltrust commented on README.md
> +```
- [ ] OPTIONAL: You found a way to exclude the swagger files from the rspec command 👍 .  

You can use/add this other command to your instructions If you want your users to get a green pass in the terminal for rswag tests:

```
rake rswag
```

Result:

![image](https://github.com/limavfabio/VenomPrecision-back-end/assets/57421823/f23d363e-8a48-462f-a19f-0d5856b4c8a5)

2023-06-24 20:24 UTC, merged